### ISSUE TITLE
fuse-zip won't handle files over 2**32 bytes (about 4.3 GB)

### ISSUE THREAD

**Issue by ghost** [refi64/fuse-zip#1]
```
> fuse-zip --version
fuse-zip version: 0.3.2
FUSE library version: 2.9.2
fusermount version: 2.9.2
using FUSE kernel interface version 7.19
```

If a zip file contains a file that's larger than 2^32 bytes, the file will show as being 2^32-1 bytes in size, and only the first 2**32-1 bytes are accessible.

This is not a purely theoretical issue since some SRTM3 GIS files have zipped files that are larger than 5.3 GB

**Comment by refi64** [comment]
This is a (very outdated) Git mirror of https://bitbucket.org/agalanin/fuse-zip/, please file this issue there.
